version: '2'

services:
  db:
    image: postgres:9.6
    volumes:
      - $HOME/persisted-data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dbmail
      - POSTGRES_PASSWORD=dbmail
      - POSTGRES_USER=dbmail

  imapd:
    build: .
    depends_on:
      - db
    environment:
      - PGDATABASE=dbmail
      - PGHOST=db
      - PGPASSWORD=dbmail
      - PGPORT=5432
      - PGUSER=dbmail
    ports:
      - "5143:143"
